version: "3"
services:
  postgres:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=test_tech
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./dockerfile
    image: project:app
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release
    depends_on:
      postgres:
        condition: service_healthy

